import { rule } from './utils/formValidationRules'
import Icons from './static/icons'

const IconsList = Object.keys(Icons)

export { default as GridItem } from './atoms/GridItem'
export { default as UiLink } from './atoms/UiLink'
export { default as Typography } from './atoms/Typography'
export { default as Image } from './atoms/Image'
export { default as Icon } from './atoms/Icon'
export { default as Container } from './atoms/Container'
export { default as Tag } from './atoms/Tag'
export { default as Badge } from './atoms/Badge'
export { default as ListItem } from './atoms/ListItem'
export { default as Loader } from './atoms/Loader'
export { default as Color } from './atoms/Color'
export { default as Label } from './atoms/Label'

export { default as Button } from './molecules/Button'
export { default as Grid } from './molecules/Grid'
export { default as Input } from './molecules/Input'
export { default as List } from './molecules/List'
export { default as Logo } from './molecules/Logo'
export { default as VideoPlayer } from './molecules/VideoPlayer'
export { default as HeaderStyledWrapper } from './molecules/HeaderStyledWrapper'
export { default as TextPanel } from './molecules/TextPanel'
// export { default as Footer } from './molecules/Footer'
export { default as HeaderMenuIcon } from './molecules/HeaderMenuIcon'
export { default as Quote } from './molecules/Quote'
export { default as QuantityInput } from './molecules/QuantityInput'
export { default as Checkbox } from './molecules/Checkbox'
export { default as Switch } from './molecules/Switch'
export { default as ListTableRow } from './molecules/ListTableRow'
export { default as VirtualizedList } from './molecules/VirtualizedList'
export { default as Comment } from './molecules/Comment'
export { default as SelectableTile } from './molecules/SelectableTile'
export { default as ThumbWithText } from './molecules/ThumbWithText'
export { default as Dropdown } from './molecules/Dropdown'

export { default as Tile } from './organisms/Tile'
export { default as TilesGrid } from './organisms/TilesGrid'
export { default as Menu } from './organisms/Menu'
export { default as ExpansionPanel } from './organisms/ExpansionPanel'
export { default as MapWithPin } from './organisms/MapWithPin'
export { default as Conveyor } from './organisms/Conveyor'
export { default as ScreensTransition } from './organisms/ScreensTransition'
export { default as Select } from './organisms/Select'
export { default as Step } from './organisms/Step'
export { default as Card } from './organisms/Card'
export { default as Slider } from './organisms/Slider'
export { default as TagsPanel } from './organisms/TagsPanel'
export { default as Drawer } from './organisms/Drawer'
export { default as LanguagesMenu } from './organisms/LanguagesMenu'
export { default as Filters } from './organisms/Filters'
export { default as SimpleTable } from './organisms/Table/Table'
export { default as Table } from './organisms/Table'
export { default as EditableCell } from './organisms/Table/components/EditableCell'
export { default as TableSummary } from './organisms/Table/components/TableSummary'
export { default as EmptyTable } from './organisms/Table/components/Empty'
export { default as HeaderMenuMobile } from './organisms/HeaderMenuMobile'
export { default as PopupAlerts } from './organisms/PopupAlerts'
export { default as InputGroupWithSelect } from './organisms/InputGroupWithSelect'
export { default as HtmlMapper } from './organisms/HtmlMapper'
export { default as Price } from './organisms/Price'
export { default as ItemCharacteristicsToChoose } from './organisms/ItemCharacteristics/ItemCharacteristicsToChoose'
export { default as ItemCharacteristicsChosen } from './organisms/ItemCharacteristics/ItemCharacteristicsChosen'
export { default as MobileBasketItem } from './organisms/Basket'
export { default as EmptyBasket } from './organisms/Basket/EmptyBasket'
export { default as BasketItemPreview } from './organisms/Basket/BasketItemPreview'
export { default as ConfirmedContacts } from './organisms/ConfirmedContacts'
export { default as TextPage } from './organisms/TextPage'

export * from './utils'
export * from './utils/imageProcessing'
export * from './utils/convertHexToRgba'
export { default as getDumbElements } from './utils/getElemetsForStories'
export { default as validate } from './utils/formValidationRules'
export { default as capitalize } from './utils/capitalize'
export { default as getTokens } from './utils/getTokens'
export { default as getGridValues } from './utils/getGridValues'

export * from './hooks/useScreenContext'
export * from './hooks/useReactRedux'
export * from './hooks/useStock'
export { default as useDebounce } from './hooks/useDebounce'
export { default as useOnScrollStop } from './hooks/useOnScrollStop'
export { default as useWindowWidth } from './hooks/useWindowWidth'
export { default as useElementRect } from './hooks/useElementRect'
export { default } from './hooks/useWindowHeight'

export * from './utilsDataRelated/filters'
export * from './utilsDataRelated/data'
export * from './utilsDataRelated/images'
export * from './utilsDataRelated/currency'
export * from './utilsDataRelated/translations'
export * from './utilsDataRelated/product'

export * from './constantsDataRelated'
export * from './constantsDataRelated/data'
export * from './constantsDataRelated/images'
export * from './constantsDataRelated/filters'
export * from './constantsDataRelated/options'
export * from './constantsDataRelated/languages'
export { default as CONFIG } from './constantsDataRelated/platformsConfig'

export * from './styles/search'
export { default as CommonGlobalStyle } from './styles/globalStyles'

export { default as ErrorBoundary } from './ErrorBoundary'

export { rule as validateOneField }
export { IconsList }
